### ISSUE TITLE
x86-64 build broken: shell_sys.c uses ARM64 dsb instruction in cmd_poke

### ISSUE THREAD

**Issue by johnjezl** [SLM-OS/SLM-Operating-System#271]
## Summary

\`make kernel PLATFORM=X86_64\` fails after commit d36a84e (Jetson GPU Phase 7):

\`\`\`
kernel/src/shell_sys.c:2460: Error: number of operands mismatch for \`ds'
\`\`\`

## Cause

\`cmd_poke\` (and possibly related commands) in \`kernel/src/shell_sys.c\` uses inline assembly that is ARM64-specific:

\`\`\`c
__asm__ volatile(\"dsb sy\" ::: \"memory\");
\`\`\`

The x86-64 assembler sees \`dsb\` and tries to interpret the second operand, producing the misleading \`ds\` error. There are 3 occurrences of \`dsb sy\` in the file; all need to be gated on ARM64 or replaced with a portable barrier.

## Suggested fix

Wrap each \`dsb sy\` with \`#if defined(__aarch64__)\` (or equivalent platform guard), and on x86-64 fall through to a \`__asm__ volatile(\"mfence\" ::: \"memory\")\` or a plain memory clobber if a full bus barrier isn't required by the caller.

## Discovered by

\`feature/usb-networking-phase0\` (#266) during a post-rebase cross-platform build check. The USB networking branch itself is unaffected; ARM64 + QEMU + Jetson + Pi 5 builds all pass.

## Repro

\`\`\`
git checkout origin/main
make kernel-clean && make kernel PLATFORM=X86_64
\`\`\`

**Comment by johnjezl** [comment]
Fixed on main — `cmd_poke`, `cmd_gpu`, and the other `dsb sy` sites in `kernel/src/shell_sys.c` now have `#if defined(PLATFORM_X86_64) mfence #else dsb sy #endif` guards. `make kernel PLATFORM=X86_64` builds clean. Verified on the rebased `feature/usb-networking-phase2` branch post-merge of latest main.
